spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    initial-size: 5
    max-active: 50
    test-while-idle: true
    validation-query: SELECT 1


logging:
  file: /share/springbootjpa.log