spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  jpa:
    database: MYSQL
    show-sql: true

server:
  port: 8070