spring:
  profiles:
    active: test

---
spring:
 profiles: development
db:
  username: 罗立兵
  password: 12345
  tables: a,b,c,d

---
data: luolibing
server:
  port: 9999
spring:
 profiles: test
 mvc:
   view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
db:
  username: admin_test
  password: 12345_test
