server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

org:
  quartz:
    scheduler:
      instanceName: ALARM_SCHEDULER
  threadPool:
    class: org.quartz.simpl.SimpleThreadPool
    threadCount: 20
    threadsInheritContextClassLoaderOfInitializingThread: true

### 默认使用yaml,指向changelog文件  classpath:/db/changelog/db.changelog-master.yaml
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml

quartz:
  enabled: true

samplejob:
  frequency: 2000